### ISSUE TITLE
Wercker APP NOT FOUND

### ISSUE THREAD

**Issue by peterdesmet** [inbo/n2kanalysis#6]
README:

<img width="823" alt="screen shot 2016-06-21 at 20 12 09" src="https://cloud.githubusercontent.com/assets/600993/16241111/813d518e-37ec-11e6-8b26-26289244eafd.png">

Maybe related: I noticed that tests were running for #5, but it failed on:

> failed: Script /tmp/1tDSc6g7vT.R failed!

**Comment by ThierryO** [comment]
Already fixed by #4 in the develop branch. The master branch will be updated in due course.
